(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "https://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "cask")
(depends-on "elpy")
(depends-on "exec-path-from-shell")
(depends-on "flx-ido")
(depends-on "magit")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "yasnippet")
(depends-on "flycheck")
(depends-on "flycheck-clojure")
(depends-on "flycheck-pos-tip")
(depends-on "wrap-region")
(depends-on "clj-refactor")
(depends-on "ac-cider")
(depends-on "nose")
(depends-on "ox-reveal")
(depends-on "rainbow-delimiters")
(depends-on "highlight-parentheses")
(depends-on "anaconda-mode")
(depends-on "smartparens")
(depends-on "use-package")
(depends-on "flycheck-pyflakes")
(depends-on "js2-mode")
(depends-on "xref-js2")
(depends-on "js2-refactor")
(depends-on "ivy")
(depends-on "pallet")
(depends-on "smex")
(depends-on "nodejs-repl")
(depends-on "pyenv-mode")
(depends-on "wc-mode")
(depends-on "markdown-mode")
(depends-on "zenburn-theme")
(depends-on "dracula-theme")